### ISSUE TITLE
Use format string for CSS class

### ISSUE THREAD

**Issue by Arcovion** [middleman/middleman-syntax#51]
Currently the chosen CSS class is automatically concatenated with the `lexer.tag` here:
https://github.com/middleman/middleman-syntax/blob/master/lib/middleman-syntax/highlighter.rb#L11

I'm thinking a more flexible approach would be to use a format string (same style as `middleman-blog`):

``` ruby
css_class: 'highlight {lang}'  # Current default, must now specify {lang} as well
css_class: '{lang}'  # No class
css_class: 'highlight'  # Omitting the language class, currently not possible
css_class: 'highlight language-{lang}'  # Prefix, currently not possible
```

Also I noticed passing `false` is coerced to a string due to the line I linked, I think it should behave as `nil` OR both `nil` and `false` should raise errors.

The [HTML5 working draft](http://www.w3.org/TR/2011/WD-html5-author-20110809/the-code-element.html) suggests this prefix idea which is why I added it. Previously I thought of just concatenating the two without a space if the `css_class` ends with a dash - but using a format string seems cleaner and means you wouldn't need another option to turn the language class off.

What do you think? It's a breaking change, so maybe adding another option like `use_format_string: true` would be needed? Will write the PR if this feature is accepted.

**Comment by bhollis** [comment]
What real problem would you be solving by making this so configurable?

**Comment by Arcovion** [comment]
No real problem per se, I know that the HTML5 spec suggests the prefix and other highlighters like highlight.js have options for it (`:class_prefix`) - it's just semantics. With this you can also remove the CSS class completely (`lexer.tag` is always added currently). It is not worth a breaking change, but gives 100% control over the output.

**Comment by bhollis** [comment]
Sure. But there's a cost to adding features, especially configurable features. Not just the code to support them, but documentation, tests, responding to issues, maintaining the feature as you evolve the library, etc. I like to make sure that a new feature meets a relatively high bar - not only that it solves a real problem somebody's having, but that it solves a problem enough people are having to outweigh the cost of one more option people have to think about.

That said, don't let me discourage you from doing whatever you want. I'm not really that involved with this project these days, and I don't want to get in the way of progress. I just figured I'd toss in some advice.

**Comment by Arcovion** [comment]
Yea that's why I wrote this instead of jumping in with a PR right away. Rouge is planning on having more options for HTML output, this would supplement that as one thing Rouge itself can't do is provide options for redcarpet and what CSS class is used. I'll wait until then though, I don't know when they plan on adding that and they're probably holding off on adding options too.

**Comment by christopherjanzen** [comment]
@arcovion have you written or modified a version of this to accommodate your needs? I'm looking to do the exact same thing so I can use prism.js. There may be an easier way for me but I've yet to figure it out.

**Comment by Arcovion** [comment]
@christopherjanzen I haven't &mdash; I would code this up but it's hard to justify a potentially breaking change until there is a new major version of [Rouge](https://github.com/jneen/rouge).

You can override it quite easily though I think, monkeypatch [this `highlight` method](https://github.com/middleman/middleman-syntax/blob/master/lib/middleman-syntax/highlighter.rb#L11) to suit your needs:
```ruby
highlighter_options[:css_class] = "language-#{lexer.tag}"
```

**Comment by christopherjanzen** [comment]
Yeah, I did get that to work. Maybe I'm thinking of a simpler solution that doesn't require rouge at all? Something that would allow me to just use fenced code blocks that automatically applies language-***. Still looking. May have to get my hands dirty.

**Comment by Arcovion** [comment]
Ah, well you need need Rouge's `find_fancy` method to automatically determine the type of code.
You could simply [write out the HTML](https://github.com/vmg/redcarpet/blob/master/lib/redcarpet.rb#L39-L43) and manually add the language class to it in the `highlight` method.

Rough idea:
```ruby
def self.highlight(code, language=nil, opts={})
  lang = (Rouge::Lexer.find_fancy(language, code) || Rouge::Lexers::PlainText).tag
  "<pre><code class=\"language-#{lang}\">#{html_escape code}</code></pre>"
end
```

**Comment by christopherjanzen** [comment]
Hmm I'll have to play around with this but thanks very much for the great leads! I think I'll be able to come up with a solution for my specific needs.

**Comment by christopherjanzen** [comment]
I ended up with this:
```ruby
"<pre><code class=\"language-#{lang}\">#{code}</code></pre>"
```
any downside to not using html_escape? I couldn't get it to work because it couldn't find the method html_escape.

**Comment by Arcovion** [comment]
You must escape it, or the browser will process the code or any entities literally instead of text.
Their `html_escape` method is [here](https://github.com/vmg/redcarpet/blob/master/lib/redcarpet.rb#L50-L59).

**Comment by christopherjanzen** [comment]
Okay, think I finally figured it out! Thanks for your help.

**Comment by zslabs** [comment]
Hi all,
What was the solution that ended up working then? Facing a similar issue where I'd like to override the default output to match what PrismJS expects and having a bit of trouble modifying that past the initial activation.

`activate :syntax`
