### ISSUE TITLE
middleman 4.0.0.rc.1 support

### ISSUE THREAD

**Issue by szines** [middleman/middleman-syntax#57]
I tried to use this gem in a middleman 4.0.0.rc.1 project and looks this gem still not support the next version.

```
Bundler could not find compatible versions for gem "middleman-core":
  In Gemfile:
    middleman-sprockets (>= 4.0.0.rc.1) ruby depends on
      middleman-core (>= 4.0.0.rc.1) ruby

    middleman (>= 4.0.0.rc.1) ruby depends on
      middleman-core (= 4.0.0.rc.1) ruby

    middleman-sprockets (>= 4.0.0.rc.1) ruby depends on
      middleman-core (>= 4.0.0.rc.1) ruby

    middleman-syntax (>= 0) ruby depends on
      middleman-core (~> 3.0.0) ruby
```

**Comment by bhollis** [comment]
I'm not sure what'll be necessary to make it support 4.0. Would you like to check out a local copy and give it a try?

**Comment by szines** [comment]
After this little modification is working for me locally. 
https://github.com/szines/middleman-syntax/commit/74926e6ccc62d37750ed8956f08849b7b00ae795
