### ISSUE TITLE
Using clipboard.js

### ISSUE THREAD

**Issue by vvo** [middleman/middleman-syntax#64]
Hi, I am using middleman 4, kramdown and middleman-syntax latest.

I am looking for a way to use https://clipboardjs.com/ in my middleman pages. But this requires that
the non-highlighted code syntax is present somewhere.

While when using middleman-syntax

In my documentation.md I have:

<pre>
Some code example:

```js
  code code code
```
</pre>

Which is then turned to:

```html
<p>Some code example:</p>

<div class="...">
  <span>code</span> <span class="..">code</span> <!-- etc... -->
</div>
```

So I cannot bind clipboard.js to the code example because the content is split for good, for syntax highlighting.

I would like to use the clipboard.js system to provide copy/paste on the code sample.

I am very new to middleman/ruby and I am sure this is not exactly the right place to ask this. But do you have some pointers for me?

Thanks.

**Comment by Arcovion** [comment]
With jQuery you could just do `$(selector).text()` which removes HTML tags.

**Comment by Arcovion** [comment]
Else, you'd need to patch the [highlighter method](https://github.com/middleman/middleman-syntax/blob/master/lib/middleman-syntax/highlighter.rb), which returns highlighted HTML from the `code` argument. 
You could simply append the original code as another HTML tag for copying, which would be hidden e.g. `<code hidden>#{code}</code>`.

**Comment by vvo** [comment]
Do you have an example on how to monkey patch the highlighter method (and where to put it?)

**Comment by vvo** [comment]
> With jQuery you could just do $(selector).text() which removes HTML tags.

I thougt so but I would then miss all indentation and linebreaks right?

**Comment by vvo** [comment]
Hey actually this works really well, silly me!

```js
document.querySelector('.code').innerText
```

Will get back the indented code raw. Thanks a lot!
