### ISSUE TITLE
Instructions for CSS are incorrect for Middleman 4

### ISSUE THREAD

**Issue by andy-twosticks** [middleman/middleman-syntax#70]
The instructions [here](https://github.com/middleman/middleman-syntax#css) assume that you can dynamically render a .scss file. I'm [told](https://github.com/middleman/middleman/issues/2101#issuecomment-312687818) that this does not work for Middleman 4.

**Comment by johnlane** [comment]
**TL;DR** for others coming here, this works in a new vanilla `markdown int foo` site:

* Create `source/stylesheets/highlighting.css.erb` as per the [instructions](https://github.com/middleman/middleman-syntax#css).
* Add to `source/stylesheets/site.css.scss`

      @import 'highlighting.css'

I've only done a quick test but I also find that it only works properly with `redcarpet` (not the default `kramdown`). If I get to the bottom of that then I will report back.

**Comment by agbodike** [comment]
Looks like this is still an issue. I believe that since rouge dynamically generates the contents of the file via erb it will only work as a .css.erb file, as sass does not compile from ERB in middleman 4.
