### ISSUE TITLE
Push v3.1.0 to rubygems? 😅

### ISSUE THREAD

**Issue by bermannoah** [middleman/middleman-syntax#75]
Hey there,

Would it be possible to release v3.1.0 of middleman-syntax sometime soon? 😅 It looks like the update with the new version of Rouge got merged [here](https://github.com/middleman/middleman-syntax/pull/74) but the [version on rubygems](https://rubygems.org/gems/middleman-syntax) is still 3.0.0. I created #76 to include the latest Rouge version but wasn't sure if I should increment the version number as this was not released.

Thanks in advance!

**Comment by gareththackeray** [comment]
Hey @tdreyno could we get the new version released as there are some fixes in Rouge we'd like to make use of.  Thanks!

**Comment by tdreyno** [comment]
@gareththackeray yes, I can get to that this weekend

**Comment by tdreyno** [comment]
Done

**Comment by tdreyno** [comment]
https://rubygems.org/gems/middleman-syntax/versions/3.3.0
