### ISSUE TITLE
Disable Line Numbers in RSS Feed

### ISSUE THREAD

**Issue by adamalbrecht** [middleman/middleman-syntax#77]
I like enabling the line numbers, but I just realized that they don't work in my RSS feed. They just appear above the entire code snippet.

Is there any way to hide them in certain contexts like this?

**Comment by markets** [comment]
Hello @adamalbrecht 👋🏼  

Unfortunately, there is no option/flag in `middleman-syntax` to disable some settings when using a different renderer (in your case, the XML for a RSS feed). But I think it can be done manually by manipulating the body (like removing undesired HTML) when rendering the feed.
